Repository terraform-google-modules/terraform-docs-samples, pull requests merged in 2023-08, with the labels that each got.

#461 fix(sql): Removed failover_target from postgres_instance_replica.
  cloud_sql/postgres_instance_replica/main.tf
Labels: waiting-response, automerge

#457 feat(compute): Add example to create a single-project reservation
  compute/reservation/create_local/main.tf
Labels: waiting-response

#488 fix: adjust "cloud_run" region tags to "cloudrun"
  run/healthchecks_liveness_probe_grpc/main.tf
  run/healthchecks_liveness_probe_http/main.tf
  run/healthchecks_startup_probe_http/main.tf
  run/healthchecks_startup_probe_tcp/main.tf
  run/jobs_create/main.tf
  run/jobs_execute_jobs_on_schedule/main.tf
  run/jobs_max_retries_create/main.tf
  run/jobs_task_parallelism_create/main.tf
  run/jobs_task_timeout_create/main.tf
Labels: waiting-for-codeowners
